
export const ICONS = {
    search: "search",
    copy: "copy",
    Uparrow: "uparrow",
    Delete: "delete",
    Heart: "heart",
    User: "user",
    MapPin: "map-pin",
    Bag: "bag",
    Star: "star",
    DownArrow: "downarrow",
    SolidHeart: "solid-heart",
    Cart: "cart",
    Home: "home",
    Office: "office",
    Plus: "plus",
    Minus: "minus",
    MinusCircle: "minus-circle",
    ChevronRight: "chevron-right",
    InboxArrowDown: "inbox-arrow-down",
    crossIcon: "crossIcon",
    crossCircle: "crossCircle",
    Truck: "truck",
    handThumbUp: "handThumbUp",
    check: "check",
    delivered: "delivered",
    edit: "edit",
    eyeShow: "eyeShow",
    eyeHide: "eyeHide",
};

export const DELIVERY_STATUS = {
    Received: "received",
    Accepted: "accepted",
    Declined: "declined",
    OutForDelivery: "out_for_delivery",
    Delivered: "delivered",
};